Update config.yml
Use grok to generate config.yml based on my github actions

https://x.com/i/grok/share/meIv12VcxRxiScWHQP9vRYspR

Signed-off-by: Marvin <velo@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,31 +1,91 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
-jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
-    docker:
-      # Specify the version you desire here
-      # See: https://circleci.com/developer/images/image/cimg/base
-      - image: cimg/base:current
+orbs:
+  docker: circleci/docker@2.2.0
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
+commands:
+  download-dependencies:
+    description: "Download Maven dependencies and pull base Docker image"
     steps:
-      # Checkout the code as the first step.
-      - checkout
       - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+          name: Download dependencies
+          command: |
+            mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies -T3
+            docker pull eclipse-temurin:11.0.22_7-jdk
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
+jobs:
+  build-and-test:
+    docker:
+      - image: cimg/openjdk:11.0
+        # Ensure Docker daemon is available
+        environment:
+          DOCKER_HOST: unix:///var/run/docker.sock
+    # Secondary Docker service image for DinD
+    # This provides the Docker daemon that Testcontainers will use
+      - image: docker:20.10.24-dind
+        environment:
+          DOCKER_TLS_CERTDIR: "" # Disable TLS for simplicity
+    environment:
+      TZ: America/Los_Angeles
+      # Optional: Configure Testcontainers to use the Docker daemon explicitly
+      TESTCONTAINERS_HOST_OVERRIDE: localhost
+    resource_class: large
+    steps:
+      - checkout
+      - download-dependencies
+      - run:
+          name: Build SQRL
+          command: mvn -T 1 -B -U -e clean verify
+          environment:
+            DATASQRL_TOKEN: $DATASQRL_TOKEN
+      - run:
+          name: Build Docker image
+          command: docker build -t sqrl-test ./sqrl-tools
+      - run:
+          name: Run conference tests
+          command: |
+            docker run -i --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls --snapshot snapshots-conference --tests tests-conference
+          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
+      - run:
+          name: Run UDF tests
+          command: |
+            docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
+          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
+      - run:
+          name: Check test results
+          command: |
+            if [ $? -ne 0 ]; then
+              echo "Test failed."
+              exit 1
+            else
+              echo "Test passed."
+            fi
+
+  # ... (other jobs remain unchanged)
+
 workflows:
-  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  pull-request-workflow:
     jobs:
-      - say-hello
+      - build-and-test:
+          context: docker-hub
+          filters:
+            branches:
+              only: /.*/
+  main-branch-workflow:
+    jobs:
+      - latest-docker-build:
+          context: docker 阳-hub
+          filters:
+            branches:
+              only:
+                - main
+                - v0.5.9-release
+  tag-workflow:
+    jobs:
+      - tag-docker-build:
+          context: docker-hub
+          filters:
+            tags:
+              only: /v[0-9]+(\.[0-9]+)*/
+            branches:
+              ignore: /.*/
